language: node_js

os:
  - linux

after_success: npm run coveralls

node_js:
- '6'

deploy:
  provider: npm
  email: m@eridem.net
  api_key:
    secure: rpuWholPc86RkwsENPEqsyW+7lT1ntX37BElbLSkPzYbLUnXL7d/S/JtznufjqWZxfzE687Wv3N+1ZuyQTNTIK/QmbQugxD1yxMagGRaP56CtvdFVcxDhMStbjCjoBbrbdmMG6+M8h/a0z1mF8Jg+XKPUSssXyQoq2MkJ73YS3OyluSnjaYSNRUaVxWklAoJhhFKNaqpgMQJbMdedGE2S/4PpIUfRL6B3iTHYrIPGJaueUteQ0UKu3YD9/4kOdbpacSgFoTHwVjQkxtmaDTRRPYxyXUggmj+1wP3jrNS7T5vnLtw4SOuw6Bl3BygYQYlR8IgZ31IvFy7DZhaaAj6ivajmDlbjg4RDIycwGm8EwEt9Zxug8PAcLwqbfC/UBICLvXDvjhGtVhsDp9uR5x/fTY9qsuyYS1pwQrE5LqIdD5iIvZsARwHCgDRzJv12bi/MXbNqWGPzb7lguEsG1xRSMTud6ouuLYI0f1z2LQCMF5ia0JBW573HLvRMFv5J0isbrhrZ57vkyQt0ds/Hq6tjevw7mBGOS+43xhALMm4n3uRAIxnogehP3NN/g7cGwxsQrbP0ahXtnV+S4KaCANR1r6BBhxX5jKaq1uOKvcxvbgbrfbIf7/9LtTEuon0awtiWou6q1TBVxfBPzfHmdXv5oLhYMb+qIkaTmbdnFrtAL8=
  on:
    tags: true
    repo: eridem/patata-cli


env:
  global:
   # Coverity
   - secure: "jG8E1JgraTJAScCcNnoDLy6PWafBlhsPIj8/HLO5xF9t2au3Xokd5trwPMNCQm6TSCltXbsEuHurH1r1rtSH0nL3nGdDC3jIzUgRMFVlPNKu4xgstl2WTlIIXSLE5CDchiTsVehOsYtJ35W1W0NjmKL0tlDLeIA4Pu4FDZk4rWfOUJruRS53yZIN+g2P/HDpodBkL3xGPUKek+CN16KlsND+Cix/46UMPk9tt5SXjMkJgyIsYNeUzwQaGp66PnEWjwbRYGBT3n2LO0G0/0dldZqA5eXMoTGgPolyae8UNUdKbrCGXHabwqyq/DDSbHubYtYRUaSMPE7aJ9+2ym+BXk+0kSSyonlbCBzzWAFzhgEDdDceMex6JwUEMQ35AXvpRVahH1JbBqI+euoM8kM5ibS1W1IoG7ncKQ9z7XMZ7ZT6oJfZk6+CcLfpReb1jVnp59iywvfjHzIgBpmE0VPSAnHmkdZJJP/QOijTEq/A14pLI+WO2AtJFfMWczn4Eoli0QUJkpZNrdDvhmFmFHFxviStbYl+NfAyXPORRQP/4Hh4aNV4jTYIs2HwH5/u9bCRKBhen63DduwVhndKLq3zAC41f4yoJaHp2bVZo1nB4WNDxR0vS+wctSLlag5+YXNLQUVQ+WXo6+vSZanY7QMQWM2bkO7CCP6meU8cM/mPyT0="

# Coverity
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# Coverity
addons:
  coverity_scan:
    project:
      name: "eridem/patata-cli"
      description: "Native testing made easy with CLI"
    notification_email: "m@eridem.net"
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search ./lib/"
    branch_pattern: "*"
