language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
install:
- npm install
deploy:
  provider: npm
  email: m@eridem.net
  api_key:
    secure: rpuWholPc86RkwsENPEqsyW+7lT1ntX37BElbLSkPzYbLUnXL7d/S/JtznufjqWZxfzE687Wv3N+1ZuyQTNTIK/QmbQugxD1yxMagGRaP56CtvdFVcxDhMStbjCjoBbrbdmMG6+M8h/a0z1mF8Jg+XKPUSssXyQoq2MkJ73YS3OyluSnjaYSNRUaVxWklAoJhhFKNaqpgMQJbMdedGE2S/4PpIUfRL6B3iTHYrIPGJaueUteQ0UKu3YD9/4kOdbpacSgFoTHwVjQkxtmaDTRRPYxyXUggmj+1wP3jrNS7T5vnLtw4SOuw6Bl3BygYQYlR8IgZ31IvFy7DZhaaAj6ivajmDlbjg4RDIycwGm8EwEt9Zxug8PAcLwqbfC/UBICLvXDvjhGtVhsDp9uR5x/fTY9qsuyYS1pwQrE5LqIdD5iIvZsARwHCgDRzJv12bi/MXbNqWGPzb7lguEsG1xRSMTud6ouuLYI0f1z2LQCMF5ia0JBW573HLvRMFv5J0isbrhrZ57vkyQt0ds/Hq6tjevw7mBGOS+43xhALMm4n3uRAIxnogehP3NN/g7cGwxsQrbP0ahXtnV+S4KaCANR1r6BBhxX5jKaq1uOKvcxvbgbrfbIf7/9LtTEuon0awtiWou6q1TBVxfBPzfHmdXv5oLhYMb+qIkaTmbdnFrtAL8=
  on:
    tags: true
    repo: eridem/patata-cli
